namespace Application.Services;

/// <summary>
/// Encapsulates the outcome of a general data processing operation.
/// </summary>
/// <param name="Succeeded">True if the operation completed successfully; otherwise, false.</param>
/// <param name="Data">An optional object containing data resulting from the operation.</param>
/// <param name="Messages">An optional collection of informational or warning messages.</param>
/// <param name="Error">An optional error message if the operation failed.</param>
public sealed record ProcessingResult(
    bool Succeeded,
    object? Data = null,
    IEnumerable<string>? Messages = null,
    string? Error = null
)
{
    /// <summary>
    /// Creates a new <see cref="ProcessingResult"/> indicating success.
    /// </summary>
    /// <param name="data">The data generated by the successful operation.</param>
    /// <param name="messages">Any relevant messages regarding the success.</param>
    /// <returns>A successful result instance.</returns>
    public static ProcessingResult Success(object? data = null, IEnumerable<string>? messages = null)
        => new ProcessingResult(true, data, messages, null);

    /// <summary>
    /// Creates a new <see cref="ProcessingResult"/> indicating failure.
    /// </summary>
    /// <param name="error">The error message describing the failure.</param>
    /// <param name="data">Any partial data that might be relevant despite failure.</param>
    /// <param name="messages">Any relevant messages regarding the failure.</param>
    /// <returns>A failed result instance.</returns>
    public static ProcessingResult Failure(string error, object? data = null, IEnumerable<string>? messages = null)
        => new ProcessingResult(false, data, messages, error);
}

/// <summary>
/// Defines the contract for services responsible for the core processing of project data pipelines.
/// </summary>
public interface IProcessingService
{
    /// <summary>
    /// Executes the full processing pipeline for a specific project synchronously.
    /// </summary>
    /// <param name="projectId">The unique identifier of the project to process.</param>
    /// <param name="overwriteLatestState">If true, the project's current state is updated with the results.</param>
    /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
    /// <returns>A result indicating the success or failure of the processing.</returns>
    Task<ProcessingResult> ProcessProjectAsync(Guid projectId, bool overwriteLatestState = true, CancellationToken cancellationToken = default);

    /// <summary>
    /// Submits a request to process a project asynchronously via a background job.
    /// </summary>
    /// <param name="projectId">The unique identifier of the project to process.</param>
    /// <param name="cancellationToken">A token to observe while waiting for the task to complete.</param>
    /// <returns>A result containing information about the queued job.</returns>
    Task<ProcessingResult> EnqueueProcessProjectAsync(Guid projectId, CancellationToken cancellationToken = default);
}